name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger workflow on commits to the main branch.
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/ml-model-api:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/ml-model-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy the application to the Fedora server
    - name: Deploy to Fedora Server
      run: |
        sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
        cd /home/milad_karimi/mlops/ml-docker-app  # Updated path
        ./deploy.sh
        EOF
